### ISSUE TITLE
Next-auth no secret

### ISSUE THREAD

**Issue by FuuKowatty** [avocado-media/nextjs-jwt-app-router#5]
I downloaded laravel-api repo

cp .env .env.example - could not that so I swapped that and copied content from .env.example to .env
composer install doesnt work, command line suggested to composer update
after that composer install
php artisan jwt:secret
php artisan migrate:fresh --seed (got error message because of permission)

After that I downloaded next repo and follwoed README
    npm install
    cp .env.example .env.local
    npm run dev

after go localhost:3000 I got error message because of the configuration 
In logs I had "no secret" info from next-auth
![image](https://github.com/avocado-media/nextjs-jwt-app-router/assets/96954875/13fcc644-c833-4e38-bb38-566d54c15413)

I tried different things like generate next-auth token and fill it 

my .env.local 
NEXT_PUBLIC_BACKEND_API_URL=http://localhost

NEXTAUTH_SECRET=/eyV6lhg7ZTZZXjEBU4UnrCyqDkFSMYrLK4LELfum9s=
NEXTAUTH_JWT_AGE=

**Comment by larswolters98** [comment]
1. Make sure the `NEXT_PUBLIC_BACKEND_API_URL` is valid
1. Try a different key, for example: `u928h28x9p`
2. Fill in `NEXTAUTH_JWT_AGE`, for example: `1209600`

**Comment by FuuKowatty** [comment]
@larswolters98 
NEXT_PUBLIC_BACKEND_API_URL  is valid because localhost opens my laravel app
different key doesnt work and filling jwt_age also :(

**Comment by larswolters98** [comment]
@FuuKowatty Can you share the log containing the error(s)?

**Comment by FuuKowatty** [comment]
@larswolters98 I already done this. Just instead of composer update I deleted composer.lock file and just run composer install. I thought the problem was by next-auth side.

Thanks for help your boilerplate will be usefull for me!
